#!/usr/bin/env bash
#The Script that sets the port 80 and give the feedback of ngix not running fr!
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
kill -9 "$(cat /run/nginx.pid)"
